### ISSUE TITLE
Adding syntax highlighing to macros

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/atom-language-asciidoc#19]
I'm playing around with trying to add some syntax highlighting to the atom-language-asciidoc, however, I'm very new at this so trying to reverse engineer what I'm seeing.

I'm trying to do something like:
````
  # Matches block macros
  #
  # Examples
  #
  #   include::test.adoc[]
  #
  {
    'begin': '^(image|include|sys|sys2|eval)::[^\s\[\]]*\['
    'end': '\]$'
    'name': 'macro.block.asciidoc'
  }
````
However, I can't get this to work. Honestly I'm not sure if it needs a "captures" or a "patterns" as I'm just playing with it.

My end goal is I'd like to see asciidoc syntax highlighting similar to what can be found when using gedit. The .lang file provided contains all the regex expressions, its just a matter of understanding how to write it in what atom expects.

**Comment by mojavelinux** [comment]
Have you been able to get the tests to run? I think running the tests will allow you to get there quicker.

It might also be nice to have a brief guide to explain how others can help. The following thread may also help:

https://discuss.atom.io/t/documentation-for-atom-grammars/6525

> # Matches block macros

A few things to note here. First, there is a difference between preprocessor directives and block macros. These should be separate since preprocessor directives can go where block macros cannot. The preprocessor directives that Asciidoctor supports are include, ifdef, ifndef, ifeval and endif. Asciidoctor doesn't support sys, sys2 and eval. The block macros are image, toc, video and audio.

**Comment by nicorikken** [comment]
A more general macro highlighting feature is already present, so this issue will be closed.
@rlopez133 Thanks for the attempt. The Gedit regexes and language structure in general is somewhat different. Don't get too distracted by it. We now have quite an extensive [contributing document](https://github.com/asciidoctor/atom-language-asciidoc/blob/master/CONTRIBUTING.adoc), to get you and others started more easily. If you get stuck, please contact.
