### ISSUE TITLE
Italics break when immediately inside footnote

### ISSUE THREAD

**Issue by andya9** [asciidoctor/atom-language-asciidoc#43]
This doesn’t work: `footnote:[_high_ hello]`

Whereas this is fine: `footnote:[hello _high_]`

**Comment by nicorikken** [comment]
Neither seems to result in highlighted italic, whereas it does render as italic.

**Comment by mojavelinux** [comment]
This is where scopes (i.e., nested patterns) are going to come into play. We need to match an inline macro, then use a nested match for inlines.

Here's how that's done:

```
{
  'name': 'markup.macro.inline.asciidoc'
  'begin': '(?<=^|\\s)(\\w+:(?:[^:]*)?\\[)(?=[^\\]]*\\])'
  'beginCaptures':
    '1': 'name': 'support.constant.asciidoc'
  'end': '\\]' 
  'endCaptures':
    '0': 'name': 'support.constant.asciidoc'
  'patterns': [
    {
      'match': '\\G[^\\]]*'
      'captures': '0': 'patterns': [{ 'include': '#inline' }]
    }
  ]
}
```

The only think I can't figure out is how to allow the macro to span multiple lines. We also should skip over an escaped backslash inside the macro brackets, but that's a separate issue.

I found the following article to be extremely helpful in understanding how to write the grammar rules, specifically handling the scopes. http://www.apeth.com/nonblog/stories/textmatebundle.html

**Comment by mojavelinux** [comment]
In this way, the inline matches only have to worry about the inner text and not the surrounding brackets.

**Comment by mojavelinux** [comment]
Note that the prefix `(?<=^|\\s)` doesn't apply for footnotes since a footnote can appear be directly adjacent to the text that precedes it.

**Comment by nicorikken** [comment]
The prefix comments relates to issue #40 as well. A nested inline capture would indeed be needed to introduce highlighting inside the macro.

**Comment by nicorikken** [comment]
I did a initial attempt in matching, but so far it doesn't seem to work as expected. Can somebody spot the flaw? Otherwise I'll hack on it some more in the future.
Commit: https://github.com/nicorikken/atom-language-asciidoc/commit/687f14d9b8555c5ad808cf18e0d65e97625e322b
Branch: https://github.com/nicorikken/atom-language-asciidoc/commits/feature/footnote-inline

**Comment by mojavelinux** [comment]
I've sent a proposal in #91.

We're still handicapped by not having a good way to have strict multi-line matches. Therefore, I decided to stick with the single line match.

If we switch to a multi-line match (begin / end), there's no way to enforce that an end be found, and no way to limit that it cannot extend past blank lines. (Grrr)

Here's a partial solution for the multi-line match which has these limitations:

```
  name: 'string.unquoted.asciidoc'
  begin: '(?<!\\\\)(footnote(?:ref)?):\\['
  beginCaptures:
    0: name: 'markup.other.footnote.asciidoc'
    1: name: 'entity.name.function.asciidoc'
  end: '(?<!\\\\)\\]'
  endCaptures:
    0: name: 'markup.other.footnote.asciidoc'
  patterns: [
    include: '#inlines'
  ]
```

There are a couple of weird things. First, we have to flip the names around so the multi-line CSS class is applied first. Otherwise, we have no way to match across multiple lines to apply a CSS class. Second is that it is very greedy and matches in cases when it shouldn't.

That's why I think we should stick with what is in the PR.

**Comment by mojavelinux** [comment]
@nicorikken The problem with your solution is that you need to attach the nested patterns to a capture match, as I have done in the PR. You only put the patterns at the top level and use `\\G` when you're using begin/end.

**Comment by mojavelinux** [comment]
I'm open to suggestion about the names I selected. I'm trying to adhere to these guidelines:

http://manual.macromates.com/en/language_grammars.html#naming_conventions

**Comment by nicorikken** [comment]
Nice fix, now I see what I was doing wrong.
Seems that you've spend some thought on the naming, so I see no reason to question your solution. Maybe document the naming conventions URL in the contributing doc?
I also noticed you introduced a lookbehinde for the `\\\\?` This pattern exists multiple times in the current grammar. It seems some refactoring will be needed on this point (now or in the near future).

**Comment by mojavelinux** [comment]
> Maybe document the naming conventions URL in the contributing doc?

Good thinking. Naming is tricky since the grammars were designed primarily for programming languages. We have to find the most logical system to reuse the existing names, then try to stick to it.

> [The lookbehind] pattern exists multiple times in the current grammar. It seems some refactoring will be needed on this point (now or in the near future).

I'm working on incorporating this change into PRs as I review the syntax patterns.

**Comment by mojavelinux** [comment]
I've sent PR #103 to document the naming conventions. It's pretty clear we still have work to do to achieve clarity and consistency. Let's keep working to update this section.
