### ISSUE TITLE
Add sections folding

### ISSUE THREAD

**Issue by antonmoiseev** [asciidoctor/atom-language-asciidoc#7]

**Comment by nicorikken** [comment]
Certainly an interesting idea. To me this seems valuable not just for sections, but also for codeblocks and other grouped lines.

**Comment by laurel** [comment]
:+1:

**Comment by nicorikken** [comment]
Apparently Atom currently only supports folding based on indentation, rather than any form of grammar-defined folding. See this forum discussion: https://discuss.atom.io/t/how-to-modify-javascript-grammar-to-support-indent-level-folding/19039 and this original issue description: https://github.com/atom/first-mate/issues/48 
One of the ways to deal with this issue, might be to introduce a dedicated folder package, as has been done for Markdown: https://atom.io/packages/markdown-folder I'd still prefer some grammar-based approach though, being available for all language to use, but that would require work from upstream Atom.

**Comment by mojavelinux** [comment]
This would truly be amazing. Folding has evaded us in the AsciiDoc world, even in VIM. It would be a killer feature for the Atom editor.

Too bad Atom doesn't do folding based on the grammar alone. Seems like a reasonable thing to support.

**Comment by mojavelinux** [comment]
Being able to fold the attribute entries in the document header would be an absolute game changer. That seems like the simplest place to start.

**Comment by mojavelinux** [comment]
Interesting to note that folding already works for block comments and consecutive line comments.

**Comment by nicorikken** [comment]
Last time I checked folding was based on indentation. Has anything changed?

**Comment by mojavelinux** [comment]
Seems like it. Or perhaps comments get special treatment. I just noticed it when I was editing.

**Comment by mojavelinux** [comment]
Moved to https://github.com/asciidoctor/atom-asciidoc-assistant/issues/10.
