### ISSUE TITLE
Idea:  create a release (patch) before each PR merge

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#87]
[Release early, release often.](https://en.wikipedia.org/wiki/Release_early,_release_often)

Small releases allows to give quickly some benefits to users.

wdyt ?

**Comment by nicorikken** [comment]
I was thinking a similar thing, when I noticed some `-beta` packages in the repository. That might be a nice way to get features early to users. Maybe also changing the latter version number might be a way of going about this: `1.1.x`. I agree with releasing more often, maybe also offer some stability though.

**Comment by ldez** [comment]
I agree.

**Comment by nicorikken** [comment]
But what practical solution? ;)

**Comment by ldez** [comment]
I don't known who can release or not.

We can use a custom Travis script, when a PR is merged it will automatically create a release (continuous delivery mode) : I'm not sure with this solution because Travis configuration is complex (to debugging), it's not a gentleman like Jenkins :wink:

**Comment by nicorikken** [comment]
Don't get me started on Jenkins, I'd call it a very conservative gentleman. I'm not sure if an automatic release is feasible, as that would require the APM credentials to be set. That would require some agreement with the Asciidoctor team. Doing small releases by hand can be done in the mean time. Maybe we can check how other Atom projects manage this.

**Comment by mojavelinux** [comment]
I've wanted to switch to using Travis for releases across the Asciidoctor ecosystem for a long time. So this is definitely the goal.

Travis provides a way to store credentials, either through their secure environment variables in .travis.yml or, more recently, through the web UI.

A secure environment variable cannot be read outside of the Travis server, so it's safe to use your own credentials. However, I realize that doing so runs the risk of being able to releasing on behalf of someone else once they move on from the project. That's why we have asciidoctor-docbot.

If we give asciidoctor-docbot permission to do releases, I can setup the secure environment variables in Travis to get it to do the release.

Of course, we'll need some sort of a script that runs in CI to detect when a release should happen, get apm to read the credentials from the environment variables, then perform the apm publish task.

See https://github.com/npm/npm/issues/7042#issuecomment-186300168

Let's start by describing each step. Then we can write a script and add the necessary configuration to .travis.yml to run it.

(Personally, I find Travis to be a very friendly assistant).

**Comment by ldez** [comment]
I will tried on my personal plugin and I will report here my experience.

**Comment by ldez** [comment]
I have created a first POC: https://github.com/ldez/exp-travis-script

I can publish every time a commit is push on the master (like merging a pull request :wink: ).

The security is ensured by an encrypted SSH key.
Encryption keys are generated and stored on my Travis account. (Even myself, I cannot know the keys!)

**Comment by ldez** [comment]
Done! :tada: 

My package https://github.com/ldez/atom-language-csv is in continuous delivery !

Some limitations:
- the publishing cannot wait AppVeyor
- the publishing doesn't wait all matrix jobs (publishing directly when running the job for Linux and stable channel)

**Comment by ldez** [comment]
You can control the publishing with Travis environment variables:
- `PUBLISH_TYPE`: default `patch`, can be change to `minor`, `major`
- `STOP_PUBLISH`: if defined prevent the publishing

wdyt?

**Comment by ldez** [comment]
@mojavelinux is it the expected behavior?

**Comment by mojavelinux** [comment]
Very promising! Nice work!

Perhaps we can use https://github.com/dmakhno/travis_after_all to trigger after the matrix build. I understand that we probably can't wait for the AppVeyor build as that's happening asynchronously.

I'm a bit confused about where the environment variables get set. I was thinking that this would be something you'd control using the git message. Basically, the git message has embedded commands that let you control the release, like "push new release [release,patch]". wdyt?

**Comment by mojavelinux** [comment]
Do you think the encryption key is easier to maintain than secure environment variables? With secure environment variables, we put the apm credentials into the environment variables, which are decoded by the build. Another option is to put these credentials in the web UI of Travis, which stores them outside the repository.

**Comment by ldez** [comment]
I use the web UI to defined secured environment variables.
Secured environment variables are use to encrypt SSH key for access to Git repository.

I defined the APM publish key in secured environment variable in Travis.

**Comment by mojavelinux** [comment]
Got it! That makes sense. :+1:

**Comment by ldez** [comment]
all is explains here: https://github.com/ldez/travis-continuous-delivery-atom-publish
- https://github.com/ldez/travis-continuous-delivery-atom-publish/blob/master/travis-secure-key.sh must be used localy to generate secured environment variables key in Travis UI (automatically publishing on Travis) and encrypted SSH key.
- https://github.com/ldez/atom-language-csv/blob/master/.travis/publish.sh mush be used in the CI to publish.

My real case: https://github.com/ldez/atom-language-csv

**Comment by mojavelinux** [comment]
As I understand it, there are two options. Put an encrypted SSH key in the repository or use a personal access token.

What I've been doing in the past is using a personal access token. You can see how I do it in the asciidoctor.org build:

https://github.com/asciidoctor/asciidoctor.org/blob/f38bc9b55ef670e06e5944749d900ec6b2ac7a24/Rakefile#L144-L149

As I understand it, it's more secure to use the encrypted SSH key in the repository.

It's a bit more complicated when we are dealing with an organization because we have to sort out which account to use. I recommend the asciidoctor-docbot GitHub account.

I'm assuming I'll need to run the travis-secure-key.sh script with the asciidoctor-docbot credentials. That part makes sense. However, I'm not sure which account to use for Travis. Maybe it doesn't matter as long as the account has write access to the repository? (which asciidoctor-docbot does).

Is my assumption correct? Should I move forward with creating the encrypted SSH key for asciidoctor-docbot?

**Comment by ldez** [comment]
There are 3 options:
- SSH key
- login/password with credentials
- github token

For Travis you are right: have a write access to the repo allow to configure Travis.

**Comment by mojavelinux** [comment]
Right, I forgot about the login/password option, but sort of omitted it because that's considered bad practice in general.

asciidoctor-docbot has write access, so we should be good there.

**Comment by ldez** [comment]
If you're ok to move forward, you can create the encrypted SSH key for asciidoctor-docbot.
I created a PR with the `.travis.yml` and the `publish.sh` script, you must edit it to save environment variable names.

[alrra/travis-after-all](https://github.com/alrra/travis-after-all) or [travis_after_all](https://github.com/dmakhno/travis_after_all) are tricks, not real stable stable system.

We can assume that the package doesn't use system dependent feature and the stable channel is our main target.

**Comment by ldez** [comment]
See  #136

**Comment by ldez** [comment]
An another and mainly element why that the publishing don't waiting all matrix jobs is not a so important problem:
All PR are build before merge, usually master is very closed to PR content.

**Comment by mojavelinux** [comment]
> All PR are build before merge, usually master is very closed to PR content.

Actually, I agree with that. Good point.

**Comment by ldez** [comment]
@mojavelinux success !! :tada: :tada: :tada:

**Comment by mojavelinux** [comment]
Score!!

**Comment by mojavelinux** [comment]
The only think left is to get the script to create a release on GitHub with some release notes. I guess since we're releasing per merge, it's just a matter of taking that commit message and adding it to the release notes section.

I also noticed that apm publish pushes to master, triggering a subsequent build. We could skip this by adding "[skip ci]" to the commit message, if apm lets you configure it.

**Comment by ldez** [comment]
actually `apm publish` doesn't allow to add annotation on a tag or customizing the commit message.

https://github.com/atom/apm/blob/master/src/publish.coffee

**Comment by mojavelinux** [comment]
Actually, that's okay. Travis supports a custom keyword match to ignore a
commit that you can specify in .travis.yml. We can search for Prepare xxx
release.

**Comment by ldez** [comment]
with AppVeyor we can skipping build by author: https://www.appveyor.com/docs/how-to/skip-build
All asciidoc-bot commits can be excluded.

**Comment by ldez** [comment]
With AppVeyor, we can skipping build by author: https://www.appveyor.com/docs/how-to/skip-build
All asciidoc-bot commits can be excluded.

@mojavelinux can you drive me to the Travis documentation for keyword matching in `.travis.yml` ?

I found this: https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build
But I don't see anything except an issue: https://github.com/travis-ci/travis-ci/issues/3005

**Comment by mojavelinux** [comment]
Oops, my memory failed me. It was AppVeyor that lets you skip builds by pattern. Well, we can at least apply the fix to AppVeyor using either method.

**Comment by anthonny** [comment]
@ldez Nice job!

> actually apm publish doesn't allow to add annotation on a tag or customizing the commit message.

i think you can tag the repo just before the `apm publish` command and use the `-t, --tags` option. 

```shell
Usage: apm publish [<newversion> | major | minor | patch | build]
       apm publish --tag <tagname>
       apm publish --rename <new-name>

...

Options:
  -h, --help    Print this usage message
  -t, --tag     Specify a tag to publish                                       [chaine de caractère]
  -r, --rename  Specify a new name for the package                             [chaine de caractère]

  Prefix an option with `no-` to set it to false such as --no-color to disable
  colored output.
```

**Comment by ldez** [comment]
To use `-t` we must update the package version manually.

And Travis is only using commit messages to detect `[ci skip]`
